-- 코드를 입력하세요
select AUTHOR_ID, AUTHOR_NAME, CATEGORY, sum(SALES * PRICE) TOTAL_SALES 
from BOOK_SALES
left join BOOK using(BOOK_ID)
left join AUTHOR using(AUTHOR_ID)
where YEAR(SALES_DATE) = '2022' and MONTH(SALES_DATE) = '01'
group by AUTHOR_ID, CATEGORY
order by AUTHOR_ID, CATEGORY DESC