-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, count(distinct USER_ID) USERS from ONLINE_SALE
left join USER_INFO using(USER_ID)
where GENDER is not null
group by YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
order by YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER